# Use a imagem base do Python
FROM python:3.8

# Defina o diretório de trabalho
WORKDIR /src

# Copie os arquivos de código e os requisitos
# COPY . /src

# Instale as dependências
RUN pip install -r requirements.txt

# Comando para iniciar a aplicação
CMD ["python", "main.py"]
