[tool.poetry]
name = "gcs-marias"
version = "0.1.0"
description = "Trabalho de GCS"
authors = ["Maria Aryene <macsantos@sga.pucminas.br>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dev-dependencies]
pytest = "^2.0.0"

